apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: pts-agent
  labels:
    app: pts-agent
spec:
  replicas: 10
  selector:
    matchLabels:
      app: pts-agent
  template:
    metadata:
      labels:
        app: pts-agent
    spec:
      containers:
      - name: pts-agent
        image: registry.cn-beijing.aliyuncs.com/ringtail/pts-agent:0.4
        env:
        - name: ENDPOINT
          value: "http://101.200.31.177/ping"
        command: ["/bin/ash","-c"]
        args: ["/usr/bin/curl $(ENDPOINT) && tail -f /dev/null"]
        resources:
          requests:
            cpu: "3.8"
      terminationGracePeriodSeconds: 0
      priorityClassName: high-priority
